### ISSUE TITLE
using Doxygen

### ISSUE THREAD

**Issue by andy5995** [lib-x/xstr#1]
Hi @the-sushi 

Have you ever considered using Doxygen to document the API, and using GitHub page to publish the doxygen-generated docs?

I was just thinking it may make a nice addition to your project (which I haven't used yet).

Good luck!

**Comment by the-sushi** [comment]
Thanks for bringing it up!  I haven't thought of it yet, I'll look into it.

**Comment by the-sushi** [comment]
Closed.  May do this in the future, not at the moment though.
