### ISSUE TITLE
xstr_push doesn't work

### ISSUE THREAD

**Issue by Erutuon** [lib-x/xstr#15]
`xstr_push` fails to add characters to the end of a string. This prints `Hello,world!`, not `Hello, world!` as expected:

```
#include <stdio.h>
#include <str.h>

#define PRINT(str) printf("'%s'\n", str);

int main (int argc, char * * argv) {
  xstr_t string;
  xstr_init(&string, sizeof "Hello, world!" + 1);
  
  xstr_cat_c(string, "Hello,");
  PRINT(*string);
  
  xstr_push(string, ' ');
  PRINT(*string);
  
  xstr_cat_c(string, "world!");
  PRINT(*string);
  
  return 0;
}

```

Doing the following replacement in two places fixed the problem:

```

_dest->val[_dest->len + 1] = ch;
_dest->val[_dest->len + 2] = 0;

// to

_dest->val[_dest->len] = ch;
_dest->val[_dest->len + 1] = 0;
```

**Comment by the-sushi** [comment]
Sorry for responding so late.  It seems to be the fault of `xstr_cat` rather than `xstr_push`.  I'll try to fix it later today.

**Comment by the-sushi** [comment]
Well I apparently lost track of this.  I'm back, fixed it: https://github.com/lib-x/xstr/commit/16ea25837a5dec1307c1f1c3ff40b7baf61689aa
