### ISSUE TITLE
Change build system

### ISSUE THREAD

**Issue by andy5995** [lib-x/xstr#3]
**Describe the bug:**
On OpenBSD, when running `build.sh`, I get this message:

`ksh: ./build.sh: No such file or directory`

Because the first line in the script is calling for `bash`, which isn't installed on OpenBSD by default.

On OpenBSD and Debian 9, there is no `CC` environmental variable defined by default so the script fails immediately:

```
Building...
./build.sh: line 6: -std=c90: command not found
Done.
```

I think setting the project up with a configure script and Makefile (by starting with a configure.ac and Makefile.am), or using a CMakeLists.txt would solve these portability issues.

If you're interested, I could set up a configure.ac and Makefile.am for the project. I'm still learning cmake and so far I like the GNU autotools better.

**Comment by the-sushi** [comment]
For now: https://github.com/lib-x/xstr/commit/6cf408a27ed0ff857e7cd38028a950b1e6526df3

>If you're interested, I could set up a configure.ac and Makefile.am for the project. I'm still learning cmake and so far I like the GNU autotools better.

Sure, thank you
