### ISSUE TITLE
clang doesn't support the -std=c90 option

### ISSUE THREAD

**Issue by andy5995** [lib-x/xstr#5]
Tried compiling on OpenBSD 6.2, but clang didn't like the std=c90 option. I was able to build after installing the gcc package.

From the [clang user's manual](http://releases.llvm.org/6.0.0/tools/clang/docs/UsersManual.html#differences-between-various-standard-modes)

>clang supports the -std option, which changes what language mode clang uses. The supported modes for C are c89, gnu89, c94, c99, gnu99, c11, gnu11, and various aliases for those modes. If no -std option is specified, clang defaults to gnu11 mode. Many C99 and C11 features are supported in earlier modes as a conforming extension, with a warning. Use -pedantic-errors to request an error if a feature from a later standard revision is used in an earlier mode.

**Comment by the-sushi** [comment]
Should be fixed with std=c89 here: https://github.com/lib-x/xstr/commit/22147d302595d741a19a9685e471249bf34f8934

**Comment by andy5995** [comment]
Confirmed.
